# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20170417_0609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
